export const methods={
  descriptive:{name:'Descriptive Research',purpose:'Systematically describes a population, situation, practice, or phenomenon—what, where, when, and how.',example:'What patterns of student participation occur during small-group mathematics instruction?',evidence:'Surveys, structured observations, classroom records, participation data, student work, and descriptive summaries.',strength:'Creates a clear, evidence-based picture of current practice.',limit:'Description alone does not establish causation.',fit:['You want to document patterns','Your main question begins with what or how','You have observable records or behaviors']},
  analytical:{name:'Analytical Research',purpose:'Examines comparisons, patterns, or relationships among practices, experiences, and outcomes.',example:"What relationship exists between weekly retrieval practice and students' vocabulary assessment performance?",evidence:'Pre/post measures, comparison data, survey scales, records, coded observations, and combined evidence.',strength:'Makes relationships and differences visible.',limit:'A relationship between variables does not automatically prove causation.',fit:['You want to compare evidence','You are examining a relationship','Your evidence has consistent measures']},
  exploratory:{name:'Exploratory Research',purpose:'Gathers preliminary information when a concern is not yet sufficiently understood.',example:'What factors do students identify as influencing their willingness to participate in classroom discussions?',evidence:'Interviews, focus groups, open-ended surveys, flexible observations, and pilot activities.',strength:'Surfaces perspectives and helps refine a question.',limit:'Findings are often context-specific and may guide later investigation.',fit:['The concern is still unclear','You want participant perspectives','You are piloting an idea']},
  case:{name:'Case Study Research',purpose:'Investigates a bounded person, group, classroom, school, program, event, or other real-world case in depth.',example:'How did one fifth-grade classroom respond to project-based science instruction?',evidence:'Interviews, observations, documents, student work, assessments, journals, and artifacts.',strength:'Provides a rich, contextual understanding using multiple sources.',limit:'Boundaries must be clear; findings should not be generalized beyond the evidence.',fit:['A bounded case is central','Context is especially important','Multiple evidence sources are available']}
} as const;
export const theories={Behaviorism:'Learning is reflected in observable changes shaped by practice, cues, reinforcement, and feedback.',Cognitive:'Learning involves attention, memory, prior knowledge, and strategies for processing information.',Constructivism:'Learners actively build understanding through inquiry, experience, and connections to prior knowledge.',Sociocultural:'Learning develops through language, collaboration, cultural tools, and participation with others.'};
export const ethics=['Instructor or supervisor approval when applicable','School, district, program, or site permission when applicable','Institutional review requirements when applicable','Informed consent or assent when required','Voluntary participation','Confidentiality and de-identification','Avoid unnecessary personally identifiable information','Secure storage and controlled access','Special care with minors and protected or vulnerable populations','Distinguish classroom improvement from research intended for public dissemination'];
export const defaultTasks=['Identify the topic or concern','Conduct an initial information search','Draft the problem and purpose','Develop the research question','Review relevant literature','Select the theoretical framework','Select the methodology and evidence approach','Complete permissions and ethics requirements','Finalize the action and data plans','Collect baseline evidence','Implement the action','Gather and organize evidence','Analyze evidence','Interpret findings and limitations','Make recommendations','Complete selected deliverables'];
export const routes=[['setup','Project setup'],['concern','Educational concern'],['method','Research method'],['theory','Learning theory'],['question','Research question'],['action-plan','Action plan'],['data-plan','Data plan & ethics'],['literature','Literature'],['timeline','Timeline'],['journal','Journal'],['analysis','Analysis'],['deliverables','Deliverables'],['review','Review']] as const;
export const thinkingPrompts:Record<string,string[]>={
  'Set up your project':['What setting can you describe without identifying participants?','Which details are required by your program—and which are optional?','What product would be genuinely useful when this inquiry ends?'],
  'Clarify the educational concern':['What have you repeatedly noticed rather than assumed?','What existing evidence makes this worth examining?','What part of the situation can you reasonably influence?'],
  'Choose a research method':['Are you describing, comparing, exploring, or studying a bounded case?','Which method best matches the purpose—not merely the available data?','What claim would this method not allow you to make?'],
  'Connect a learning theory':['How does the theory explain learning in your planned action?','What would this lens help you notice?','What might this theory overlook in your context?'],
  'Build your research question':['Can evidence reasonably address every part of the question?','Does the wording avoid assuming success?','Is the scope feasible in one action-research cycle?'],
  'Plan the action':['What will happen consistently in every implementation?','How will you know whether the action occurred as planned?','What adjustment will you make if context disrupts the cycle?'],
  'Plan evidence and safeguard participants':['What is the minimum evidence needed to answer the question?','How will each source add a different perspective?','Could any field identify or harm a participant?'],
  'Organize the literature':['Which claim will this source help you understand?','Have you verified every bibliographic detail?','Where do sources agree, differ, or leave a gap?'],
  'Timeline and tasks':['Which permission or dependency could delay the project?','What must happen before evidence collection begins?','Where should you leave time for reflection and revision?'],
  'Implementation journal':['What actually happened—not what was supposed to happen?','What contextual event could explain today’s evidence?','What should remain private unless intentionally submitted?'],
  'Analyze and reflect':['What pattern is calculated versus interpreted?','What contradictory evidence deserves attention?','What conclusion would go beyond the evidence?'],
  'Prepare deliverables':['Which verified notes belong in each section?','What still needs the student’s explanation or approval?','Which format best serves the intended audience?'],
  'Review readiness':['Can another educator understand and implement the plan?','Are evidence, ethics, and analysis aligned with the question?','What is the first concrete action after approval?']
};
export const phaseFor=(title:string)=>title.includes('Review')||title.includes('deliverable')?'Share & act':title.includes('Analyze')||title.includes('journal')?'Learn from evidence':title.includes('Plan the action')||title.includes('evidence')||title.includes('literature')||title.includes('Timeline')?'Design the inquiry':'Define the inquiry';
