export const methods={
  descriptive:{name:'Descriptive Research',purpose:'Systematically describes a population, situation, practice, or phenomenon—what, where, when, and how.',example:'What patterns of student participation occur during small-group mathematics instruction?',evidence:'Surveys, structured observations, classroom records, participation data, student work, and descriptive summaries.',strength:'Creates a clear, evidence-based picture of current practice.',limit:'Description alone does not establish causation.',fit:['You want to document patterns','Your main question begins with what or how','You have observable records or behaviors']},
  analytical:{name:'Analytical Research',purpose:'Examines comparisons, patterns, or relationships among practices, experiences, and outcomes.',example:"What relationship exists between weekly retrieval practice and students' vocabulary assessment performance?",evidence:'Pre/post measures, comparison data, survey scales, records, coded observations, and combined evidence.',strength:'Makes relationships and differences visible.',limit:'A relationship between variables does not automatically prove causation.',fit:['You want to compare evidence','You are examining a relationship','Your evidence has consistent measures']},
  exploratory:{name:'Exploratory Research',purpose:'Gathers preliminary information when a concern is not yet sufficiently understood.',example:'What factors do students identify as influencing their willingness to participate in classroom discussions?',evidence:'Interviews, focus groups, open-ended surveys, flexible observations, and pilot activities.',strength:'Surfaces perspectives and helps refine a question.',limit:'Findings are often context-specific and may guide later investigation.',fit:['The concern is still unclear','You want participant perspectives','You are piloting an idea']},
  case:{name:'Case Study Research',purpose:'Investigates a bounded person, group, classroom, school, program, event, or other real-world case in depth.',example:'How did one fifth-grade classroom respond to project-based science instruction?',evidence:'Interviews, observations, documents, student work, assessments, journals, and artifacts.',strength:'Provides a rich, contextual understanding using multiple sources.',limit:'Boundaries must be clear; findings should not be generalized beyond the evidence.',fit:['A bounded case is central','Context is especially important','Multiple evidence sources are available']}
} as const;
export const theories={Behaviorism:'Learning is reflected in observable changes shaped by practice, cues, reinforcement, and feedback.',Cognitive:'Learning involves attention, memory, prior knowledge, and strategies for processing information.',Constructivism:'Learners actively build understanding through inquiry, experience, and connections to prior knowledge.',Sociocultural:'Learning develops through language, collaboration, cultural tools, and participation with others.'};
export const ethics=['Instructor or supervisor approval when applicable','School, district, program, or site permission when applicable','Institutional review requirements when applicable','Informed consent or assent when required','Voluntary participation','Confidentiality and de-identification','Avoid unnecessary personally identifiable information','Secure storage and controlled access','Special care with minors and protected or vulnerable populations','Distinguish classroom improvement from research intended for public dissemination'];
export const defaultTasks=['Identify the topic or concern','Conduct an initial information search','Draft the problem and purpose','Develop the research question','Review relevant literature','Select the theoretical framework','Select the methodology and evidence approach','Complete permissions and ethics requirements','Finalize the action and data plans','Collect baseline evidence','Implement the action','Gather and organize evidence','Analyze evidence','Interpret findings and limitations','Make recommendations','Complete selected deliverables'];
export const routes=[['setup','Project setup'],['concern','Educational concern'],['method','Research method'],['theory','Learning theory'],['question','Research question'],['action-plan','Action plan'],['data-plan','Data plan & ethics'],['literature','Literature'],['timeline','Timeline'],['journal','Journal'],['analysis','Analysis'],['deliverables','Deliverables'],['review','Review']] as const;
