-- Apply in a new Supabase project. Uses explicit Data API grants for 2026 defaults.
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, title text not null default 'Untitled action research project', program text, course text, instructor text, term text, setting text, status text not null default 'draft' check(status in('draft','ready','active','complete')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_responses (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, section_key text not null, response_key text not null, content text not null default '', version integer not null default 1, updated_at timestamptz not null default now(), unique(project_id,section_key,response_key));
create table public.research_method_selections (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null unique references public.projects(id) on delete cascade,method text,case_subtype text,data_approach text,updated_at timestamptz not null default now());
create table public.data_sources (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,position integer not null default 0,name text not null default '',details jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.literature_sources (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,position integer not null default 0,title text not null default '',details jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_tasks (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,position integer not null default 0,title text not null,description text,date date,completed boolean not null default false,updated_at timestamptz not null default now());
create table public.research_cycles (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,cycle_number integer not null check(cycle_number>0),status text not null default 'plan',created_at timestamptz not null default now(),unique(project_id,cycle_number));
create table public.journal_entries (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,cycle_id uuid references public.research_cycles(id) on delete cascade,entry_date date not null default current_date,content jsonb not null default '{}',submitted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.qualitative_codes (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,label text not null,color text,memo text,created_at timestamptz not null default now());
create table public.qualitative_evidence (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,code_id uuid references public.qualitative_codes(id) on delete set null,excerpt text not null default '',is_contradictory boolean not null default false,created_at timestamptz not null default now());
create table public.quantitative_datasets (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,name text not null,metadata jsonb not null default '{}',data jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.deliverables (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,type text not null,title text not null,outline jsonb not null default '[]',submitted_at timestamptz,updated_at timestamptz not null default now());
create table public.course_groups (id uuid primary key default gen_random_uuid(),instructor_id uuid not null references auth.users(id) on delete cascade,name text not null,join_code_hash text not null unique,created_at timestamptz not null default now());
create table public.group_memberships (id uuid primary key default gen_random_uuid(),group_id uuid not null references public.course_groups(id) on delete cascade,student_id uuid not null references auth.users(id) on delete cascade,joined_at timestamptz not null default now(),unique(group_id,student_id));
create table public.feedback (id uuid primary key default gen_random_uuid(),group_id uuid not null references public.course_groups(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,instructor_id uuid not null references auth.users(id) on delete cascade,student_id uuid not null references auth.users(id) on delete cascade,section_key text not null,body text not null,resolved boolean not null default false,created_at timestamptz not null default now());
create table public.ethics_checkpoints (project_id uuid primary key references public.projects(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,checks jsonb not null default '[]',reviewed_at timestamptz);

do $$ declare t text; begin foreach t in array array['profiles','projects','project_responses','research_method_selections','data_sources','literature_sources','project_tasks','research_cycles','journal_entries','qualitative_codes','qualitative_evidence','quantitative_datasets','deliverables','course_groups','group_memberships','feedback','ethics_checkpoints'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy profiles_select on public.profiles for select to authenticated using((select auth.uid())=id); create policy profiles_insert on public.profiles for insert to authenticated with check((select auth.uid())=id); create policy profiles_update on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id); create policy profiles_delete on public.profiles for delete to authenticated using((select auth.uid())=id);
do $$ declare t text; begin foreach t in array array['projects','project_responses','research_method_selections','data_sources','literature_sources','project_tasks','research_cycles','journal_entries','qualitative_codes','qualitative_evidence','quantitative_datasets','deliverables','ethics_checkpoints'] loop execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = owner_id)',t||'_select',t); execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = owner_id)',t||'_insert',t); execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = owner_id) with check ((select auth.uid()) = owner_id)',t||'_update',t); execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = owner_id)',t||'_delete',t); end loop; end $$;
-- Instructor tables are denied by default until a protected app_metadata role and verified membership policies are enabled.
revoke all on all tables in schema public from anon; grant usage on schema public to authenticated; grant select,insert,update,delete on public.profiles,public.projects,public.project_responses,public.research_method_selections,public.data_sources,public.literature_sources,public.project_tasks,public.research_cycles,public.journal_entries,public.qualitative_codes,public.qualitative_evidence,public.quantitative_datasets,public.deliverables,public.ethics_checkpoints to authenticated;
create index projects_owner_idx on public.projects(owner_id); create index responses_project_idx on public.project_responses(project_id,section_key); create index data_sources_project_idx on public.data_sources(project_id,position); create index literature_project_idx on public.literature_sources(project_id,position); create index tasks_project_idx on public.project_tasks(project_id,position); create index journal_project_idx on public.journal_entries(project_id,entry_date); create index deliverables_project_idx on public.deliverables(project_id,type);
